name: CI

on:
  push:
    branches: [main]
    paths: ["Formula/**"]
  pull_request:
    paths: ["Formula/**"]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Audit formula
        run: brew audit --tap="$GITHUB_REPOSITORY"

      - name: Install formula (build from source)
        run: brew install --build-from-source --formula amatsuzero/m3u8dl/n-m3u8dl-re

      - name: Test formula
        run: brew test amatsuzero/m3u8dl/n-m3u8dl-re
